/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GithubCard: typeof import('./components/GithubCard.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    LinkBtn: typeof import('./components/LinkBtn.vue')['default']
    LinkIcon: typeof import('./components/LinkIcon.vue')['default']
    LinkImg: typeof import('./components/LinkImg.vue')['default']
    LinkTitleBtn: typeof import('./components/LinkTitleBtn.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    SnsRow: typeof import('./components/SnsRow.vue')['default']
    TagChip: typeof import('./components/TagChip.vue')['default']
    TwitterCard: typeof import('./components/TwitterCard.vue')['default']
    TwitterEmbedded: typeof import('./components/TwitterEmbedded.vue')['default']
    WakaTimeCard: typeof import('./components/WakaTimeCard.vue')['default']
    WebsiteCard: typeof import('./components/WebsiteCard.vue')['default']
    YoutubeCard: typeof import('./components/YoutubeCard.vue')['default']
    ZennCard: typeof import('./components/ZennCard.vue')['default']
  }
}
