/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    HobbyActivitiesCard: typeof import('./components/profile/HobbyActivitiesCard.vue')['default']
    HomePage: typeof import('./pages/HomePage.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    MoreBtn: typeof import('./components/MoreBtn.vue')['default']
    ProfileAvatar: typeof import('./components/ui/ProfileAvatar.vue')['default']
    ProfileInfoCard: typeof import('./components/profile/ProfileInfoCard.vue')['default']
    ProfileLinksCard: typeof import('./components/profile/ProfileLinksCard.vue')['default']
    ProfileOverviewCard: typeof import('./components/profile/ProfileOverviewCard.vue')['default']
    ProfileProjectsCard: typeof import('./components/profile/ProfileProjectsCard.vue')['default']
    ProfileRssCard: typeof import('./components/profile/ProfileRssCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsCard: typeof import('./components/profile/SkillsCard.vue')['default']
    SocialLinks: typeof import('./components/profile/SocialLinks.vue')['default']
    Subheader: typeof import('./components/Subheader.vue')['default']
    TagChip: typeof import('./components/TagChip.vue')['default']
    WakaTimeCard: typeof import('./components/profile/WakaTimeCard.vue')['default']
  }
}
