name: deploy-node

on:
  push:
    branches: [master]
    paths-ignore:
      - 'backend/**'
      - 'tools/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: npm ci, build
        run: |
          export NODE_ENV=development
          npm ci
          export NODE_ENV=production
          npm run build --if-present

      - name: s3 sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_REGION: ap-northeast-1
          AWS_S3_BUCKET: mcre.info
          SOURCE_DIR: dist

      - name: invalidate cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_REGION: ap-northeast-1
          DISTRIBUTION: EDE74EPVAHP4C
          PATHS: /*
